### ISSUE TITLE
useState snippet is not working correctly

### ISSUE THREAD

**Issue by Lamer217** [chillios-ts/vscode-react-javascript-snippets#246]
This is what the snippet returns:
('description' added by me when trying out)
![image](https://user-images.githubusercontent.com/62716818/156017754-2b5dc4b5-8bb6-4be3-8d87-d583d533bf3c.png)

**Comment by dsznajder** [comment]
https://user-images.githubusercontent.com/17621507/156024032-fce590b5-9a85-40bb-b966-4aac524bfd96.mov

@Lamer217 hmm are you using newest version? I just tried it on my own and it works fine 🤔

**Comment by Lamer217** [comment]
Seems like everything should be working, but somehow it doesn't. Tried also reinstalling. What info can I provide for easier debugging?

https://user-images.githubusercontent.com/62716818/156372618-6473828b-e7aa-4a33-b032-e7238efa72f8.mp4

**Comment by ashuvax** [comment]
#255 
I put a fix to it in the file

**Comment by priyomukul** [comment]
`useStateSnippet` is working properly for me (not from snippet search though) but it's not updating the import at the top automatically. 

is there any way to fix it. options to solve it? @dsznajder

**Comment by ice-chillios** [comment]
@priyomukul probably not as it would need to trigger 2 hooks on one input :/ I'm annoyed as you with this 😓 I might ask someone from VSCode team, but currently I'm really out of time :/.
